### PR TITLE
Apply changes in Python scripts

### PR DESCRIPTION
**Pull request by mhanifi**
Update the master branch with the most recent changes on the Python scripts.

### CODE REVIEW

**Comment by robin-raymond** [comment]
@mhanifi  This merger has conflicts so it can't be accepted "as is", and we have a specific methodology when we merge to master -- we merge all submodules to their master branch (or master-uwp branch depending if we are maintaining an intentional master fork) and only after do we merge the SDK root folder.

We are still awaiting more feedback on releases/m71 to indicate that it's preferred to the current master. I think we are nearing that point. Can you provide indication of what is your intention with the PR? 

Thanks!

**Comment by mhanifi** [comment]
@robin-raymond We need the changes in the python scripts in order to create NuGet package. The pipeline for CI/CD is pointing to master branch which has the latest code but not the latest changes in the Python scripts.

**Comment by SergioOpenPeer** [comment]
@mhanifi Please update, pipeline to build from releases/m71 branch. Master won't be updated for sure in next couple of weeks.

**Comment by robin-raymond** [comment]
We are not ready to merge releases/m71 to master and we would not do it this way due to the way sub repos work. Going to close this PR and we will merge when it's ready for master. If you need releases/m71 on your own master then I'd suggest forking and doing that merge but I'd not recommend it unless that's something you absolutely must have.

**Pull request closed without merging**
